# Generated by Django 4.1.1 on 2023-03-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('instructor_name', models.CharField(max_length=255)),
                ('training_type', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
