# Generated by Django 4.1.1 on 2023-03-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0003_users_training_current_capacity_user_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='user_log',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
