# Generated by Django 4.1.1 on 2023-03-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0005_alter_user_trial_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclubmgmt.user'),
        ),
    ]
