# Generated by Django 4.1.1 on 2023-03-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0006_alter_activitylog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
