# Generated by Django 4.1.1 on 2023-03-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0007_alter_activitylog_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclubmgmt.training')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthclubmgmt.user')),
            ],
        ),
    ]
