# Generated by Django 4.1.1 on 2023-03-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0009_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='location_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='healthclubmgmt.location'),
        ),
        migrations.AddField(
            model_name='user_log',
            name='location_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='healthclubmgmt.location'),
        ),
    ]
