# Generated by Django 4.1.1 on 2023-03-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthclubmgmt', '0011_alter_training_location_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
    ]
